# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LightThemUp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  source 'https://github.com/CocoaPods/Specs.git'
  use_frameworks!
  pod 'SideMenuController'
  pod 'ImagePicker'
  pod 'SwiftOverlays', '~> 3.0.0'
  pod 'Alamofire', '~> 4.0'
  pod 'JASON', '~> 3.0'
  # Pods for Example

end
